### ISSUE TITLE
[Bug] Reverts to the user at the top of the list after UI reload

### ISSUE THREAD

**Issue by cp2004** [OctoPrint/OctoPrint-AutoLoginConfig#10]
See bug report https://github.com/OctoPrint/OctoPrint/issues/4766

Steps to reproduce:

1. Have more than one user configured
2. Select any user other than the first
3. Save settings
4. Reload UI
5. Save settings again
6. It has reverted to the top of the list

**Comment by timur-tabi** [comment]
I'm surprised that I'm the first to expose this bug.  It seems like something that would have been noticed already.

**Comment by cp2004** [comment]
As am I - over 2 years and 650+ people running the plugin, and no one ever wants to use the 2nd user in the list. Well, I have pushed a fix tagged as 0.2.1. I was able to easily reproduce the issue following the steps above and am no longer able to whatever I try, so hopefully that works out OK.
