### ISSUE TITLE
Constant Notices to Update.

### ISSUE THREAD

**Issue by ryancasler** [OctoPrint/OctoPrint-AutoLoginConfig#2]
I have installed the latest version, then I updated from the prompt within OctoPrint.  Every time the server starts, I get a notice telling me I need to update.  
![image](https://user-images.githubusercontent.com/30270489/99473238-2f08ec80-2918-11eb-9bf3-2c96f7c55060.png)

It appears that the version that it is reporting back to OctoPrint, is incorrect.  

![image](https://user-images.githubusercontent.com/30270489/99473292-4d6ee800-2918-11eb-8c40-24aa402b08ac.png)

I've updated 4 times now and it still gives me the prompt to update.

**Comment by cp2004** [comment]
That's unfortunate. Looks like because there are two tags with no changes, it picks the earlier one to build the distro, but the SW update finds the later one. Will sort it out later today, maybe fixing the description can be the change 🙂

**Comment by cp2004** [comment]
Update loop has now been fixed with release of 0.1.2. Still getting used to using the new automation I setup for versioning, since everything is generated automatically and messed it up by tagging the same commit twice. Thanks for reporting!

**Comment by ryancasler** [comment]
<strike>No problem.  Do i have to wait for this update to be wrapped into another distro because I am still only seeing 0.1.1 as the current release within OctoPrint.</strike>
Nevermind.  I had to go into Advanced Options and click "Force Check for Update" and it got the new version.

![image](https://user-images.githubusercontent.com/30270489/99580236-3c23eb00-29ad-11eb-9e29-e53f02ac4104.png)
