### ISSUE TITLE
Support Hostnames eg: octoprint.local [Request]

### ISSUE THREAD

**Issue by ymboc** [OctoPrint/OctoPrint-AutoLoginConfig#4]
Our 3D Printer connects to the network/internet via a wireless connection shared from a nearby workstation (Windows 10 hotspot).

On that PC; the associated raspberry pi/octoprint is addressable by the DN 'octoprint.local' which is associates to ip 192.168.137.x

With the list of local networks properly configured ( 192.168.0.0/16 )...

When connecting to octoprint using the IP address, the AutoLoginLocal functions as expected

However, when connecting to octoprint using the DN 'octoprint.local',  AutoLoginLocal does not work as expected.

**Comment by cp2004** [comment]
Please note that this plugin is just for configuring Auto Login Local, it doesn't actually implement it (and this is instead done by something deep down in Core OctoPrint).

That said, I am involved in development of OctoPrint so lets see what I can think of. I'm surprised that this doesn't work - the hostname resolution is for the server, whereas AAL is evaluating the client IP.

Could you upload the logs (`octoprint.log`), and I will see what it *thinks* the IP is coming from the client.

**Comment by ymboc** [comment]
When gathering the requested logs -- (generating new entries; leveraging browser incognito modes) -- I discovered that there is no issue. This works as intended after-all.

How did I make this error? How did I not discover this sooner? 
My (non-incognito) browser sessions were secretly auto-completing the url to specific configuration pages that the 'default' user doesn't have access to -- hence bringing me to the login prompt.

IP-based url entry didn't have the same auto-complete history in the browser sessions; avoiding the 'issue' and convincing me I was facing a bug
