### ISSUE TITLE
[Bug] AutoLogin is no longer working with OctoPrint 1.8.3

### ISSUE THREAD

**Issue by b-morgan** [OctoPrint/OctoPrint-AutoLoginConfig#8]
**Describe the bug**

AutoLogin is no longer working with OctoPrint 1.8.3

**To Reproduce**
Clear steps to reproduce the behavior:

1. Configure AutoLogin under OctoPrint 1.8.2
2. Verify that auto login is working
3. Upgrade to OctoPrint 1.8.3
4. Discover that auto login is not working

**Logs**

[octoprint.log](https://github.com/OctoPrint/OctoPrint-AutoLoginConfig/files/9612131/octoprint.log)

**Expected behavior**

I expect auto login to work with OctoPrint 1.8.3

**Versions**

OctoPrint: 1.8.3
Plugin: 0.2.0
OS running OctoPrint (if OctoPi, include version): OctoPi 0.18.0
OS & Browser (If UI issue) of machine _accessing_ OctoPrint: Windows 10, Firefox 105.0

**Further notes**

**Comment by cp2004** [comment]
This plugin doesn't have anything to do with the auto login process, it is just a configuration interface. Please report issues with the actual auto login process to the main OctoPrint repository.
